---
title: "un_graphs"
format: html
editor: visual
---

```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
source("un_data.R")
```

```{r}
pop_tidy <- population %>%
  select(Year, TotalPop1July, TotalPopMale1July, TotalPopFemale1July) %>%
  pivot_longer(cols = -Year,
               names_to = "PopulationType",
               values_to = "Population")

pop_tidy_july <- pop_tidy %>%
  mutate(PopulationType = recode(PopulationType,
                                 "TotalPop1July" = "Total",
                                 "TotalPopMale1July" = "Male",
                                 "TotalPopFemale1July" = "Female"))


ggplot(pop_tidy_july, aes(x = Year, y = Population, color = PopulationType)) +
  geom_line() +
  geom_point() +
  labs(title = "Population from 1950 - 2100",
       color = "Population Type",
       x = "Year",
       y = "Population",
       color = "Type") +
  theme_minimal()

```

```{r}
# life expectancy comparison

ggplot(life_expectancy, aes(Year)) +
  geom_line(aes(y = `at Birth`, color = "Total")) +
  geom_line(aes(y = `at Birth, Male`, color = "Male")) +
  geom_line(aes(y = `at Birth, Female`, color = "Female"))
```
